### ISSUE TITLE
headers object doesn't accept the defined schema

### ISSUE THREAD

**Issue by thelinuxlich** [ecyrbe/zodios#141]
I have a parameter with the Header type defined as:

```js
{
  type: 'Header',
  name: 'token',
  schema: z.object({
    Authorization: z.string().transform(s => {
      return `Basic ${Buffer.from(s + ':').toString('base64')}`
    }),
  }),
}
```

But when I try to use it like this:
```js
zoop.getMarketplaceTransactions({
  params: { id: marketplace_id },
  headers: {
    token: {
      Authorization: key,
    },
  },
})
```

The typechecker complains about the object shape: 
![image](https://user-images.githubusercontent.com/5043/191318849-e7de085b-53e9-43be-bc97-90b739d6cfcf.png)

**Comment by thelinuxlich** [comment]
Changing the schema to z.string() instead of z.object() solved it

**Comment by ecyrbe** [comment]
yes, use a string schema.

But i'll recommend using axios `auth` parameter or use plugin token to inject auth headers
cf : 
https://www.zodios.org/docs/client/plugins#authorization-with-token-plugin
or
axios auth
https://www.zodios.org/docs/client#request-options

**Comment by ecyrbe** [comment]
if you want to send manually anyway here the correct setup
```
{
  type: 'Header',
  name: 'Authorization',
  schema: z.string().transform(s => {
      return `Basic ${Buffer.from(s + ':').toString('base64')}`
    }),
}
```

**Comment by thelinuxlich** [comment]
I'm declaring like that because I don't want auth to be optional

**Comment by ecyrbe** [comment]
i see.  
if you are using basic auth for each endpoint, i could create a basic auth plugin that you could use all of them without needed to require you to pass it manually for each call.  
like this  :  
```
client.use(pluginBasicAuth(() => {
   return { username: 'my user', password: 'my password' }
 }));
```
and now it will be injected in all your calls

if you are interested in this. feel free to create a plugin request.
since token plugin is dedicated to do the same but for bearer token that are more common in APIs
