### ISSUE TITLE
findEndpointErrorsByAlias is not matching error from a mutation alias which has path parameter

### ISSUE THREAD

**Issue by QzCurious** [ecyrbe/zodios#269]
As the title state, `findEndpointErrorsByAlias` has bug. It's better to reproduce the bug with [testing code](https://github.com/QzCurious/zodios/blob/828c1ab07b2693d64840d16d7ef299d4ef7231e5/src/utils.test.ts#L76-L128). Because then we can log the state inside zodios.

![image](https://user-images.githubusercontent.com/38932402/209355261-bfc27f40-816b-4af5-a1fb-f7f1f5a14bbf.png)

I currently have no idea how to fix the bug. Because `findEndpointErrorsByAlias` don't have enough information to compare the two.

**Comment by ecyrbe** [comment]
this is fixed in `v10.7.6` without waiting for v11. thanks to @maantje for the fix.
v11 will still tie error handling to client to allow better error handling.

Since v11 will come in match (since it will require TS 5.0), i'll have some time to improve client to have a non throwable version (and still have throwable one). this way, error handling will also have a simpler path : 
```ts
const client = new Zodios(baseurl, myApi, { enableExceptions: false } );
const { data: users, error } = await client.getUsers();
if( error ) {
  // typed error
}
```
