### ISSUE TITLE
Support 204 (empty) response status 

### ISSUE THREAD

**Issue by vltansky** [ecyrbe/zodios#307]
I would expect 204 a valid empty response. Right now as I understand according to [docs](https://www.zodios.org/docs/api/api-definition) you can define only one valid response, while you can define multiple error responses.

OpenApi example:
```
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ExampleResponse"
                }
              }
            }
          },
          "204": {
            "description": "NoContent"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseDetails"
                }
              }
            }
          },
```

**Comment by ecyrbe** [comment]
When designing an API, you usually want to return consistant results for one REST endpoint.
Because, then you'll have to handle it as an edge case.
Are you stuck with a concrete example where you need this ?
At the moment as a workaround you can make a single schema that accepts both empty result and a complete result.
Zodios client and server will not check the status if it's between 200 and 299.
Just that openAPI docs will not show it.
