### ISSUE TITLE
`app.use((err, req, res, next) => {})` get implicit any for TypeScript 5.2.2

### ISSUE THREAD

**Issue by hanayashiki** [ecyrbe/zodios#565]
Version: @zodios/express 10.6.1, zod 3.22.4, @types/express 4.17.21

```ts
export const app = zodiosApp(apis);

//              ⬇️ Parameter 'err' implicitly has an 'any' type.ts(7006)
app.use((err, _req, res, next) => {
    next(err);
});
```

This seems to be a problem in function overloading:

```ts
interface ZodiosUse<Context extends ZodObject<any>> {
    use(...handlers: Array<ZodiosRouterContextRequestHandler<Context>>): this;
    use(handlers: Array<ZodiosRouterContextRequestHandler<Context>>): this;
    use(errorHandler: ZodiosRouterContextErrorHandler<Context>): this;
    use(path: string, ...handlers: Array<ZodiosRouterContextRequestHandler<Context>>): this;
    use(path: string, handlers: Array<ZodiosRouterContextRequestHandler<Context>>): this;
}
```

If I just remove all but `use(errorHandler: ZodiosRouterContextErrorHandler<Context>): this;`, the implicit any error is gone. Or if I just remove `use(...handlers: Array<ZodiosRouterContextRequestHandler<Context>>): this;`

**Comment by soulchild** [comment]
You might be on to something here with function overloading being the issue and this could even be related to https://github.com/ecyrbe/zodios/issues/505#issuecomment-1691582056

In every project I'm using Zodios in, I'm eventually seeing more and more "implicit any" warnings which go away when restarting the TS language server in VS Code or sometimes even just saving my current file. Looks like TS gets confused as to what typings to pick or something like that (just like you suggested).

Unfortunately, it seems @ecyrbe is on an extended hiatus at the moment. I sincerely hope, he's gonna come back to work on Zodios because it is such an awesome library. 🙏

**Comment by hanayashiki** [comment]
> You might be on to something here with function overloading being the issue and this could even be related to [#505 (comment)](https://github.com/ecyrbe/zodios/issues/505#issuecomment-1691582056)
> 
> In every project I'm using Zodios in, I'm eventually seeing more and more "implicit any" warnings which go away when restarting the TS language server in VS Code or sometimes even just saving my current file. Looks like TS gets confused as to what typings to pick or something like that (just like you suggested).
> 
> Unfortunately, it seems @ecyrbe is on an extended hiatus at the moment. I sincerely hope, he's gonna come back to work on Zodios because it is such an awesome library. 🙏

This issue doesn't resolve even if you restart the ts server. And it happens without complex settings.(even when the api is empty array)
